# Generated by Django 5.0.1 on 2025-11-13 07:04

from django.db import migrations, models


def ensure_unique_emails(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    seen = set()

    for user in User.objects.all().order_by('id'):
        orig_email = (user.email or '').strip()

        if not orig_email:
            # Generate a deterministic placeholder email
            user.email = f'user{user.id}@placeholder.local'
        else:
            base_email = orig_email.lower()
            if base_email in seen:
                local, _, domain = base_email.partition('@')
                if not domain:
                    domain = 'placeholder.local'
                suffix = 1
                new_email = f"{local}+dup{suffix}@{domain}"
                while new_email in seen:
                    suffix += 1
                    new_email = f"{local}+dup{suffix}@{domain}"
                user.email = new_email
            else:
                user.email = base_email

        seen.add(user.email.lower())
        user.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(ensure_unique_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
