# Generated by Django 5.0.1 on 2025-11-14 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_questionbankentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('zoom', 'Zoom'), ('google_classroom', 'Google Classroom'), ('microsoft_teams', 'Microsoft Teams'), ('canvas', 'Canvas'), ('blackboard', 'Blackboard')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'integration_type')},
            },
        ),
        migrations.CreateModel(
            name='GoogleClassroomIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('classroom_id', models.CharField(blank=True, max_length=255)),
                ('lms_integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_classroom_settings', to='integrations.lmsintegration')),
            ],
            options={
                'verbose_name': 'Google Classroom Integration',
                'verbose_name_plural': 'Google Classroom Integrations',
            },
        ),
        migrations.CreateModel(
            name='ZoomIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=255)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('lms_integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_settings', to='integrations.lmsintegration')),
            ],
            options={
                'verbose_name': 'Zoom Integration',
                'verbose_name_plural': 'Zoom Integrations',
            },
        ),
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=255, unique=True)),
                ('meeting_url', models.URLField()),
                ('topic', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('join_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to='courses.lesson')),
                ('zoom_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='integrations.zoomintegration')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('auto_sync', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='courses.course')),
                ('lms_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='integrations.lmsintegration')),
            ],
            options={
                'ordering': ['-synced_at'],
                'unique_together': {('course', 'lms_integration')},
            },
        ),
    ]
